### ISSUE TITLE
Validation failure should cause the grunt task to fail

### ISSUE THREAD

**Issue by cvrebert** [praveenvijayan/grunt-html-validation#2]
We're looking at using this in Bootstrap, FYI: https://github.com/twbs/bootstrap/pull/9396

**Comment by mdo** [comment]
To be clear, failures should fail, but warnings shouldn't. Not sure if that's the case as it is now, but I wanted to mention that just in case.

**Comment by praveenvijayan** [comment]
@mdo @cvrebert  - If we break the process upon an error, it will be a tedious job for a user to give validate command again & again, if there are so many files to validate.  

A 'stoponerror' option has been added and setting it to true will stop html-validator upon error.

**Comment by cvrebert** [comment]
@praveenvijayan We don't want it to stop upon an error per se, we just want the validation task as a whole to indicate to Grunt that there were failure(s).

**Comment by praveenvijayan** [comment]
@cvrebert - a JSON report at the end of the validation will work?

**Comment by praveenvijayan** [comment]
@cvrebert  - Added a consolidated JSON report at the end of validation with filename and error messages. 

``` javascript
[{
    "filename": "test/html/home.html",
    "error": [{
        "lastLine": 8,
        "lastColumn": 23,
        "message": "Element title must not be empty.",
        "messageid": "html5",
        "explanation": "    <p class=\"helpwanted\">\n      <a\n        href=\"feedback.html?uri=;errmsg_id=html5#errormsg\"\n\ttitle=\"Suggest improvements on this error message through our feedback channels\" \n      >&#x2709;</a>\n    </p>\n",
        "type": "error"
    }]
}]
```
