### ISSUE TITLE
"Validated skipping"

### ISSUE THREAD

**Issue by callumacrae** [praveenvijayan/grunt-html-validation#23]
```
cm-mbp:test callumacrae$ grunt validation
Running "validation:files" (validation) task
Validated skipping..app/index.html
Validated skipping..app/test.html
```

The text is green, but it isn't validating the files, even when I change the files. Any ideas why?

**Comment by praveenvijayan** [comment]
Already validated files won't validate again. use $grunt validate --reset=true in order to revalidate files.

**Comment by callumacrae** [comment]
Surely they should validate again when changed, though?

**Comment by noducks** [comment]
+1 for them to be able to validate again when changed.

**Comment by dynamicdan** [comment]
I found this to be a bug although I understand the caching need/concept.

How can we ensure files with changes are re-validated? Create a hash of the file (based on content, file size or something) and use that to work out if the file has changed and therefore should be re-validated? I believe grunt-ftpush does something like this to avoid uploading files that haven't changed.

EDIT: just created a new issue #47
