### ISSUE TITLE
Validation causes grunt task list to quit.

### ISSUE THREAD

**Issue by noducks** [praveenvijayan/grunt-html-validation#25]
I have a grunt task list something like this:

```
grunt.registerTask('dev', ['jshint',  'validation',  'concat', 'watch']);
```

but 'validation' quits the task list, so concat and watch don't get called, even if there are no reported errors. Am not sure if there is an option flag or something else I'm missing?

**Comment by callumacrae** [comment]
I'm experiencing this, as well.

**Comment by praveenvijayan** [comment]
#25 & #26 fixed, validation can run without failing other subsequent tasks.

**Comment by shazron** [comment]
This bug re-appears in v0.1.14 and up (tested with v0.1.14, 0.1.15, 0.1.16). 

If I revert back to v0.1.13, I don't see this bug.

**Comment by shazron** [comment]
Please re-open this, this bug has re-appeared.

**Comment by marksyzm** [comment]
Still happening in 0.1.18. Please re-open.

**Comment by marksyzm** [comment]
I noticed this doesn't happen when the `reset` option is set to `true`
