### ISSUE TITLE
Running multiple sub-tasks fails after first.

### ISSUE THREAD

**Issue by noducks** [praveenvijayan/grunt-html-validation#26]
I have set up my grunt file as so...

```
    validation: {
        options: {
            reset: true
        },
        indexHtml: {
            src: 'app/views/index.html'
        },
        homeHtml: {
            src: 'app/views/home.html'
        }
    }
```

but if I have a task list like this:

```
 grunt.registerTask('dev', ['clear', 'jshint', 'validation', 'concat']);
```

the expected behaviour would be that index.html should be validated then home.html, however the validation exits after the first indexHtml task, and the homeHtml task isn't run. 

The following task list also fails after the first file (index.html),

```
 grunt.registerTask('dev', ['clear', 'jshint', 'validation:indexHtml', 'validation:homeHtml', 'concat']);
```

so, this may be related to my previous issue https://github.com/praveenvijayan/grunt-html-validation/issues/25

If I use grunt-watch, I am able to call the indexHtml and homeHtml as they are changed, if I watch both of the files separately.

**Comment by praveenvijayan** [comment]
Thanks noducks. Issue fixed.
