### ISSUE TITLE
Loop issue.

### ISSUE THREAD

**Issue by dstroot** [praveenvijayan/grunt-html-validation#4]
The utility needs some work but I don't have the time to search through the code loops:
- If you only have one page the code seems to loop twice and you get an undefined error.  
- If you have many pages the last page is not validated
- JSON output mis-spelled.  validation-staus.json  (staus?)

Looping issue is caused when called in this manner:

```
// -----------------------------------
//
// TASK: validation  [Validate the html] 
//
// -----------------------------------

validation: {
  options: {
    reset: true,
  },
  files: {
    src: ["_site/**/*.html"]
  }
},
```

**Comment by praveenvijayan** [comment]
Thanks @dstroot  Loop issue & typo fixed.

**Comment by dstroot** [comment]
You rock!  Thanks for fixing this!
