### ISSUE TITLE
html-validation causes imagemin to not process files?

### ISSUE THREAD

**Issue by tleen** [praveenvijayan/grunt-html-validation#50]
Strange bug, some other grunt plugins stop working when _preceeded_ by validation. They run, but don't seem to see their input files. It starts after v0.1.13. 

I made a [simple example](https://github.com/tleen/grunt-html-validation-failures-test) using [imagemin](https://github.com/gruntjs/grunt-contrib-imagemin), but saw it also with [aws_s3](https://github.com/MathieuLoutre/grunt-aws-s3), and some mocha tests.

Can anyone else run my example and see if it happens to them as well?

**Comment by vladikoff** [comment]
@tleen see https://github.com/praveenvijayan/grunt-html-validation/pull/52 that might address your issue. Let me know how it goes!
