### ISSUE TITLE
Plugin seems totally broken

### ISSUE THREAD

**Issue by vladikoff** [praveenvijayan/grunt-html-validation#51]
Hey there, first of all this is a great idea for a plugin. However we need to fix some stuff up.
### Nevermind, ignore this issue

I'm gonna PR a test update.

**Comment by XhmikosR** [comment]
@vladikoff: I totally agree with what you suggested :)

As for JSHint, I remember I fixed all issues some time ago...

**Comment by vladikoff** [comment]
@XhmikosR I was looking at this https://github.com/praveenvijayan/grunt-html-validation/blob/master/tasks/html_validation.js#L127-L128 and it seems like the recursive behavior causes issues such as noted here: https://github.com/praveenvijayan/grunt-html-validation/issues/50
