### ISSUE TITLE
Consider using h1 elements as top-level headings only

### ISSUE THREAD

**Issue by XhmikosR** [praveenvijayan/grunt-html-validation#55]
We are getting "Consider using h1 elements as top-level headings only (all h1 elements are treated as top-level headings by many screen readers and other tools).".

Even though I add this in `relaxerror`, I still get the warnings.

``` js
validation: {
  options: {
    charset: 'utf-8',
    doctype: 'HTML5',
    failHard: true,
    reset: true,
    relaxerror: [
      'Attribute ontouchstart not allowed on element body at this point.',
      'Bad value X-UA-Compatible for attribute http-equiv on element meta.',
      'Consider using h1 elements as top-level headings only (all h1 elements are treated as top-level headings by many screen readers and other tools).'
    ]
  },
  files: {
    src: '_site/**/*.html'
  }
},
```

Is this because this isn't really an error but a help message? Is there any way to suppress this kind of errors?

**Comment by XhmikosR** [comment]
For reference  https://travis-ci.org/twbs/ratchet/builds/25766130

**Comment by cvrebert** [comment]
@XhmikosR You need to escape the parentheses because `relaxerror` takes regexps.

**Comment by XhmikosR** [comment]
@cvrebert: I'm not sure I get it. `\(` will still result in the same stuff plus it's unnecessary escape. Am I missing something?

**Comment by lefoy** [comment]
+1, I also have this error.

**Comment by lefoy** [comment]
It works if I use this: `'^Consider using the h1'`

**Comment by XhmikosR** [comment]
This doesn't seem to happen anymore so I guess it was an upstream issue.
