### ISSUE TITLE
Error on validation

### ISSUE THREAD

**Issue by thomaspons** [praveenvijayan/grunt-html-validation#9]
Hi,

I've got this error using grunt-html-validation.

I'm using Yeoman and generator-angular.

I'm behind a corporate proxy.

Error: connect ETIMEDOUT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete](net.js:892:19)

Any idea ? Is it me ?

**Comment by thomaspons** [comment]
I see the problem ! 

In superagent just add this lines under var mod = exports.protocols[url.protocol];

if(process.env.http_proxy) {
    var proxy = parse(process.env.http_proxy);
    options.port = proxy.port;
    options.path = this.url;
    options.host = proxy.hostname;
    mod = exports.protocols[proxy.protocol];
}

But now i've got another issue my corporate proxy block the post method and send me a 501 ! I don't know why.

Here the original patch for superagent : https://gist.github.com/shigeki/2921169

**Comment by ojacquemart** [comment]
I got the same issue behind a proxy.
Do you manage to get rid of the ETIMEDOUT error?

**Comment by ojacquemart** [comment]
The PR #20 should solve the issue :)

**Comment by thomaspons** [comment]
Ok ! 

I'll will wait for the merge and the update of the docs ;) ! 

Really nice work

**Comment by praveenvijayan** [comment]
Thanks @ojacquemart & @thomaspons merged.
